[book]
title = "cobalamine"
authors = ["erhant"]
language = "en"
src = "corrin"

# uses KaTeX instead of MathJax, much better interop
[preprocessor.katex]
after = ["links"]

# converts mermaid drawings to SVG
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["./vendor/mermaid-center.css"]
additional-js = ["./vendor/mermaid.min.js", "./vendor/mermaid-init.js"]
git-repository-url = "https://github.com/erhant/cobalamine"
default-theme = "light"
